FROM python:3.9-alpine

RUN apk add --no-cache \
    gcc \
    musl-dev \
    python3-dev \
    wget

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY idp.py .

EXPOSE 5001

CMD ["python", "idp.py"]