services:
  cve-2014-6271:
    build: .
    container_name: cve-2014-6271-lab
    ports:
      - "8080:80"
    networks:
      - labnet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cve-2014-6271.rule=Host(`cve-2014-6271.local`)"
      - "traefik.http.services.cve-2014-6271.loadbalancer.server.port=80"

networks:
  labnet:
    external: true
    name: labnet
