version: '3.8'

services:
  cve-2016-10033:
    build: .
    container_name: cve-2016-10033-lab
    ports:
      - "9021:80"
    networks:
      - labnet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cve-2016-10033.rule=Host(`cve-2016-10033.local`)"
      - "traefik.http.services.cve-2016-10033.loadbalancer.server.port=80"

networks:
  labnet:
    external: true
    name: labnet
